repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e05c5c0818279e5ac248ac9e954431ba58865e61  # frozen: v0.15.7
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: 631208b7aac2daa8b707f55e7331f9112b0e062d  # frozen: v1.44.0
    hooks:
      - id: typos
