name: Test
"on":
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v7.6.0
        with:
          python-version: "3.14"
      - uses: actions/checkout@v4
      - run: uv run pytest -vvv --cov .
